config/routes.rb
require 'sessions_helper'

SciRate::Application.routes.draw do
  root 'feeds#index'

  get '/search', to: 'papers#search', as: 'papers_search'

  post '/api/scite/:paper_uid', to: 'api#scite',
       as: :scite, paper_uid: /.+/
  post '/api/unscite/:paper_uid', to: 'api#unscite',
       as: :unscite, paper_uid: /.+/
  post '/api/subscribe/:feed_uid', to: 'api#subscribe',
       as: :subscribe, feed_uid: /.+/
  post '/api/unsubscribe/:feed_uid', to: 'api#unsubscribe',
       as: :unsubscribe, feed_uid: /.+/
  post '/api/hide_from_recent/:comment_id', to: 'api#hide_from_recent',
       as: :hide_from_recent
  post '/api/settings', to: 'api#settings'

  post '/api/resend_confirm', to: 'api#resend_confirm', as: :resend_confirm
  post '/api/create_stripe_checkout', to: 'api#create_stripe_checkout'

  resources :comments do
    member do
      post :edit
      post :delete
      post :restore
      post :upvote
      post :unvote
      post :report
      post :unreport
      post :reply
    end
  end
  get '/comments', to: 'comments#index'
  get '/comments/:id/history', to: 'comments#history', as: 'comment_history'

  get '/auth/:provider/callback', to: 'sessions#omniauth_callback'
  get '/auth/:provider/disconnect',
    to: 'sessions#omniauth_disconnect', as: 'omniauth_disconnect'
  get '/auth/failure', to: 'sessions#omniauth_failure', as: 'omniauth_failure'
  post '/auth/create', to: 'sessions#omniauth_create', as: 'omniauth_create'

  get '/signup',   to: 'users#new', as: 'signup'
  post '/signup',  to: 'users#create'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/logout',   to: 'sessions#destroy'
  get '/signin',   to: redirect('/login')
  get '/signout',  to: redirect('/logout')

  get '/about',    to: 'static_pages#about'
  get '/version',  to: 'static_pages#version'
  get '/conduct',  to: 'static_pages#conduct'
  get '/legal',    to: 'static_pages#legal'
  get '/moderation',    to: 'static_pages#moderation'


  if Settings::JOBS_VISIBLE
    get '/jobs/success', to: 'static_pages#job_success'
    get '/jobs/submit',  to: 'static_pages#submit_job'
    get '/jobs/about',   to: 'static_pages#about_jobs'

    get '/jobs', to: 'static_pages#list_jobs'
  end

  get '/reset_password', to: 'password_resets#new', as: :reset_password
  post '/reset_password', to: 'password_resets#create'

  get '/reset_password/:id', to: 'password_resets#confirm', as: :reset_password_confirm
  post '/reset_password/:id', to: 'password_resets#submit'

  get '/settings', to: 'users#settings'
  post '/settings', to: 'users#settings'

  get '/settings/password', to: 'users#settings_password'
  post '/settings/password', to: 'users#settings_password'

  #resources :users, only: [:new, :create, :edit, :update, :destroy, :admin]
  get '/users/:id/subscriptions', to: 'users#subscriptions', as: 'subscriptions_user'
  get '/users/:id/activate/:confirmation_token', to: 'users#activate', as: 'activate_user'
  get '/feeds', to: 'users#feeds', as: 'feeds'

  get '/arxiv/:paper_uid/scites', to: 'papers#scites', paper_uid: /(.+\/.+|\d+.\d+)(v\d)?/, as: 'paper_scites'
  get '/arxiv/:feed/comments', to: 'comments#index', feed: /.+/, as: 'feed_comments'
  get '/arxiv/*paper_uid', to: 'papers#show', paper_uid: /.+\/.+|\d+.\d+(v\d)?/, as: 'paper'
  get '/arxiv/:feed', to: 'feeds#show', feed: /.+/, as: 'feed'#, constraints: NeedsUserConstraint

  get '/admin', to: 'admin/base#index', as: 'admin'
  post '/admin/alert', to: 'admin/base#alert', as: 'admin_alert'

  get '/admin/users/:username/edit', to: 'admin/users#edit', as: 'admin_edit_user'
  post '/admin/users/:username/update', to: 'admin/users#update', as: 'admin_update_user'
  post '/admin/users/:username/become', to: 'admin/users#become', as: 'admin_become_user'

  get '/:username/download_scites', to: 'users#download_scites', username: /.+/, as: 'user_download_scites'
  get '/:username/scites', to: 'users#scites', username: /.+/, as: 'user_scites'
  get '/:username/comments', to: 'users#comments', username: /.+/, as: 'user_comments'
  get '/:username/papers', to: 'users#papers', username: /.+/, as: 'user_papers'
  get '/:username', to: 'users#activity', username: /.+/, as: 'user'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                 :integer          not null, primary key
#  user_id            :integer          not null
#  score              :integer          default(0), not null
#  cached_votes_up    :integer          default(0), not null
#  cached_votes_down  :integer          default(0), not null
#  hidden             :boolean          default(FALSE), not null
#  parent_id          :integer
#  ancestor_id        :integer
#  created_at         :datetime
#  updated_at         :datetime
#  content            :text             not null
#  deleted            :boolean          default(FALSE), not null
#  paper_uid          :text             default(""), not null
#  hidden_from_recent :boolean          default(FALSE), not null
#

class Comment < ActiveRecord::Base
  belongs_to :user, touch: true
  belongs_to :paper, foreign_key: :paper_uid, primary_key: :uid, touch: true

  belongs_to :parent, class_name: "Comment" # Immediate reply ancestor
  belongs_to :ancestor, class_name: "Comment" # Highest-level reply ancestor

  validates :user, :paper, :content, presence: true

  has_many :reports, class_name: "CommentReport"
  has_many :children, foreign_key: 'parent_id', class_name: 'Comment'

  has_many :history, class_name: "CommentChange"

  belongs_to :last_change, class_name: "CommentChange" # Last user who altered this comment

  scope :visible, -> { where(hidden: false, deleted: false) }

  after_create do
    # Record initial creation event
    record_change!(CommentChange::CREATED, self.user_id)

    # Track who we've emailed so we don't send twice for the same comment
    emailed_users = []

    # Email on comment replies
    if parent && parent.user.email_about_replies
      UserMailer.comment_alert(parent.user, self).deliver_later
      emailed_users[parent.user.id] = true
    end

    # Email people who claim this paper via their arXiv author identifier
    paper.claimants.each do |author|
      if author.email_about_comments_on_authored
        UserMailer.comment_alert(author, self).deliver_later unless emailed_users[author.id]
        emailed_users[author.id] = true
      end
    end

    # Email any sciters who have opted in to alerts on scited papers
    paper.sciters.each do |sciter|
      if sciter.email_about_comments_on_scited
        UserMailer.comment_alert(sciter, self).deliver_later unless emailed_users[sciter.id]
        emailed_users[sciter.id] = true
      end
    end
  end

  after_save do
    paper.refresh_comments_count!
    user.refresh_comments_count!
  end

  after_destroy do
    paper.refresh_comments_count!
    user.refresh_comments_count!
  end

  acts_as_votable

  # Records a comment change and the user who was responsible
  def record_change!(event, user_id)
    cc = CommentChange.create!(
      comment_id: self.id,
      user_id: user_id,
      event: event,
      content: self.content
    )

    update!(last_change_id: cc.id) unless event == CommentChange::CREATED
  end

  def soft_delete!(user_id)
    update!(deleted: true)
    record_change!(CommentChange::DELETED, user_id)
  end

  def restore!(user_id)
    update!(deleted: false)
    record_change!(CommentChange::RESTORED, user_id)
  end

  def edit!(content, user_id)
    update!(content: content)
    record_change!(CommentChange::EDITED, user_id)
  end

  def submit_trackback
    trackback_url = "https://arxiv.org/trackback/#{paper_uid}"

    title = "#{user.fullname}: #{self.content[0..99]}"
    title += "..." if self.content.length > 100

    data = {
      title: title,
      excerpt: self.content,
      url: "https://scirate.com/arxiv/#{paper.uid}##{self.id}",
      blog_name: "SciRate"
    }

    u = URI.parse(trackback_url)
    res = Net::HTTP.start(u.host, u.port, :use_ssl => u.scheme == 'https') do |http|
      http.post(u.request_uri, URI.encode_www_form(data), { 'Content-Type' => 'application/x-www-form-urlencoded; charset=utf-8' })
    end

    if res.code != '200'
      SciRate::Application.notify_error("Error from arXiv trackback: #{res.code} #{res.body}")
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:edit, :delete, :restore, :upvote, :unvote, :report, :unreport, :reply, :history]

  before_action  :check_moderation_permission, only: [:edit, :delete, :restore]

  def index
    @page = [1, params.fetch(:page, 1).to_s.to_i].max
    @per_page = 50

    feed_uids = if params[:feed]
      # Comments on papers in a particular feed
      feed_uids = Feed.find_related_uids([params[:feed]])
    elsif signed_in?
      # Comments on papers in the user's home timeline
      sub_uids = current_user.subscriptions.pluck(:feed_uid)
      feed_uids = Feed.find_related_uids(sub_uids)
    end

    query = if feed_uids.nil?
      Comment.joins(:user, :paper)
             .where(deleted: false, hidden: false, hidden_from_recent: false)
    else
      Comment.joins(:user, paper: :categories)
             .where(deleted: false, hidden: false, hidden_from_recent: false)
             .where(categories: { feed_uid: feed_uids })
    end


    @pagination = WillPaginate::Collection.new(@page, @per_page, query.count)

    @comments = query.order('comments.id DESC')
                     .limit(@per_page)
                     .offset((@page-1)*@per_page)
                     .select('DISTINCT ON (comments.id) comments.id',
                             'comments.content',
                             'comments.created_at',
                             'comments.updated_at',
                             'papers.uid AS paper_uid',
                             'papers.title AS paper_title',
                             'users.username AS user_username',
                             'users.fullname AS user_fullname')
  end

  def history
    return check_moderation_permission if @comment.deleted
  end

  def create
    comment_params = params.require(:comment).permit(:paper_uid, :content)

    @comment = current_user.comments.build(comment_params)

    if not(@comment.paper.locked) and not(current_user.is_spammer?)
        @comment.save!
        @comment.submit_trackback
        flash[:comment] = { status: :success, content: "Comment posted." }
    end

    redirect_to @comment.paper
  end

  def edit
    unless @comment.content == params[:content] # Don't record edit if same
      @comment.edit!(params[:content], current_user.id)
    end
    render json: 'success'
  end

  def delete
    # soft delete - hide
    @comment.soft_delete!(current_user.id)

    flash[:comment] = { status: 'success', raw: "Comment deleted. <a data-method='post' href='#{restore_comment_path(@comment.id)}'>(undo)</a>" }

    redirect_to request.referer || @comment.paper
  end

  # Restore a deleted comment
  def restore
    @comment.restore!(current_user.id)

    flash[:comment] = { status: 'success', content: "Comment restored." }
    redirect_to request.referer || @comment.paper
  end

  def upvote
    unless comment_owner?
      @comment.upvote_from(current_user)
      render json: 'success'
    else
      render json: "can't upvote own comment"
    end
  end

  def unvote
    @comment.unvote(voter: current_user)
    render json: 'success'
  end

  def report
    @comment.reports.create(user_id: current_user.id)
    render json: 'success'
  end

  def unreport
    @comment.reports.where(user_id: current_user.id).destroy_all
    render json: 'success'
  end

  def reply
    @reply = current_user.comments.build(
      paper_uid: @comment.paper_uid,
      parent_id: @comment.id,
      ancestor_id: @comment.ancestor_id || @comment.id,
      content: params[:content]
    )

    if not(@comment.paper.locked) and not(current_user.is_spammer?)
        if @reply.save
            flash[:comment] = { status: 'success', content: "Comment posted." }
        else
            flash[:comment] = { status: 'error', content: "Error posting comment." }
        end
    end

    redirect_to @reply.paper
  end

  private

    def check_moderation_permission
      if !signed_in? || (!comment_owner? && !current_user.can_moderate?)
        not_found
      end
    end

    def comment_owner?
      @comment.user_id == current_user.id
    end

    def find_comment
      @comment = Comment.find(params[:id])
    end

    def find_feed_ids(feed)
      feed.children.pluck(:uid) + [feed.uid]
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_abbr_comment.html.slim
.abbr-comment data-comment-id=(abbr_comment.id)
  .tex2jax
    - if abbr_comment.paper_title.length > 75
      a href="/arxiv/#{abbr_comment.paper_uid}##{abbr_comment.id}"
        = sanitize(abbr_comment.paper_title[0..72])
        | ...
    - else
      a href="/arxiv/#{abbr_comment.paper_uid}##{abbr_comment.id}"
        = abbr_comment.paper_title
  span.username
    a href="/#{abbr_comment.user_username}"
      = abbr_comment.user_fullname
  =< timeago(abbr_comment.created_at)
  blockquote.tex2jax style="margin-top: 5px;"
    .body
      = simple_format(strip_tags(abbr_comment.content[0..299]))
    - if abbr_comment.content.length > 300
      a href="/arxiv/#{abbr_comment.paper_uid}##{abbr_comment.id}"
        |  ...(continued)
  - if signed_in? && current_user.can_moderate?
    .moderate
      | #{status_warning} <a class="hide-from-recent">hide from recent comments</a>

app/views/comments/_comment.html.slim
- @voted = signed_in? ? current_user.voted_as_when_voted_for(comment) : nil

div.comment class=('mine' if signed_in? && current_user.id == comment.user_id) class=('deleted' if comment.deleted || comment.hidden) class=('voted' if @voted) class=('reply' if comment.parent) data-id=(comment.id) data-markup=(comment.content unless comment.deleted || comment.hidden)
  a name=(comment.id)
  - if comment.deleted && @has_children[comment.id]
    | (deleted comment)
  - elsif comment.hidden && @has_children[comment.id]
    | (hidden comment)
  - elsif (!comment.deleted && !comment.hidden)
    .votes
      div.upvote class=('active' if @voted == true)
        i.fa.fa-arrow-up
    .nonvotes
      - if @user
        div= link_to comment.paper.title, comment.paper
      = link_to comment.user.fullname, comment.user
      - if comment.parent
        |  in reply to
        a< href="##{comment.parent.id}" = comment.parent.user.fullname
      span.timeago
        =< timeago(comment.created_at)
        - if comment.cached_votes_up > 0 || comment.cached_votes_down > 0
          |  (<span class="score">#{comment.cached_votes_up-comment.cached_votes_down}</span> points)
      .body.tex2jax
        = simple_format(strip_tags(comment.content))
      p
        - unless comment.last_change.nil?
          | #{comment.last_change.event.capitalize} <a class="timeago-link" href="/comments/#{comment.id}/history">#{timeago(comment.last_change.created_at)}</a> by #{user_link(comment.last_change.user)}
      - if @paper && current_user
        .actions
          a.permalink href="##{comment.id}" permalink
          - if current_user.id == comment.user_id 
                - if @paper.locked?
                    = link_to 'delete', delete_comment_path(comment), method: :post
                - else
                    a.edit edit
                    = link_to 'delete', delete_comment_path(comment), method: :post
          - else
            - if comment.reports.exists?(user_id: current_user.id)
                a.unreport reported (undo)
            - else
              a.report report
          - if not(@paper.locked)
              a.reply reply
          - if current_user.can_moderate?
            .moderate
              | #{status_warning} <a class="edit">edit</a>
              =< link_to 'delete', delete_comment_path(comment), method: :post
  div style="clear: both;"

app/views/comments/_deleted_comment.html.slim
/ TODO: this could be refactored with _comment.html.slim, it's just
/ a little fiddly to do so

- comment = deleted_comment

div.comment data-id=(comment.id) data-markup=(comment.content)
  .votes
    div.upvote class=('active' if @voted == true)
      i.fa.fa-arrow-up
  .nonvotes
    - if @user
      div= link_to comment.paper.title, comment.paper
    = link_to comment.user.fullname, comment.user
    - if comment.parent
      |  in reply to #{link_to comment.parent.user.fullname, comment.parent.user}
    span.timeago
      =< timeago(comment.created_at)
      - if comment.cached_votes_up > 0 || comment.cached_votes_down > 0
        |  (<span class="score">#{comment.cached_votes_up-comment.cached_votes_down}</span> points)
    .body.tex2jax
      = simple_format(strip_tags(comment.content))
    p
      - unless comment.last_change.nil?
        | #{comment.last_change.event.capitalize} <a class="timeago-link" href="/comments/#{comment.id}/history">#{timeago(comment.last_change.created_at)}</a> by #{user_link(comment.last_change.user)}
    .actions
      a.permalink href="##{comment.id}" permalink
      - if current_user.id == comment.user_id || current_user.can_moderate?
        a.edit edit
        = link_to 'restore', restore_comment_path(comment), method: :post
      - else
        - if comment.reports.exists?(user_id: current_user.id)
            a.unreport reported (undo)
        - else
          a.report report

app/views/comments/history.html.slim
- provide :title, "Comment #{@comment.id}: Revision history"

#commentHistory.container
  .row
    h1
      | Revision history for comment #{@comment.id}
  - @comment.history.each do |change|
    - if change.event == CommentChange::CREATED
      .row.event class=(change.event)
        | #{user_link(change.user)} commented on <a href="/arxiv/#{@comment.paper_uid}##{@comment.id}">#{@comment.paper.title}</a> #{timeago(change.created_at)}
        .content.well.tex2jax
          = simple_format(strip_tags(change.content))

    - elsif change.event == CommentChange::EDITED
      .row.event class=(change.event)
        | Edited by #{user_link(change.user)} #{timeago(change.created_at)}
        .content.well.tex2jax
          = simple_format(strip_tags(change.content))

    - elsif change.event == CommentChange::DELETED
      .row.event class=(change.event)
        | Deleted by #{user_link(change.user)} #{timeago(change.created_at)}

    - elsif change.event == CommentChange::RESTORED
      .row.event class=(change.event)
        | Restored by #{user_link(change.user)} #{timeago(change.created_at)}

app/views/comments/index.html.slim
- if @feed
  - title = @feed.fullname
- else
  - title = signed_in? ? "Home feed" : "Top arXiv papers"

- provide :title, title

.col-md-10.feed-center
  - cache [:feed, @feed, current_user] do
    header.feed-header class=(@feed ? '' : 'home')
      .row
        - if @feed
          .col-md-10
            h1
              = @feed.fullname
              |  (#{@feed.uid})
          .col-md-2
            = render 'feeds/subscribe', feed: @feed, subscribed: signed_in? && @feed.subscriptions.exists?(user_id: current_user.id)
        - else
          .col-md-10
            h1= title
            - if signed_in?
              = link_to "edit subscriptions", feeds_path, class: 'view-subs'
            - else
              = link_to "sign in to customize", login_path, class: 'view-subs'
  .row
    .col-md-9
      ul.nav.nav-tabs.mobile
        li
          a href="/"
            | Papers
        li.active
          a href="/comments"
            | Comments
      = render partial: "comments/abbr_comment", collection: @comments
      = will_paginate @pagination
                = will_paginate @pagination