config/routes.rb
require 'sessions_helper'

SciRate::Application.routes.draw do
  root 'feeds#index'

  get '/search', to: 'papers#search', as: 'papers_search'

  post '/api/scite/:paper_uid', to: 'api#scite',
       as: :scite, paper_uid: /.+/
  post '/api/unscite/:paper_uid', to: 'api#unscite',
       as: :unscite, paper_uid: /.+/
  post '/api/subscribe/:feed_uid', to: 'api#subscribe',
       as: :subscribe, feed_uid: /.+/
  post '/api/unsubscribe/:feed_uid', to: 'api#unsubscribe',
       as: :unsubscribe, feed_uid: /.+/
  post '/api/hide_from_recent/:comment_id', to: 'api#hide_from_recent',
       as: :hide_from_recent
  post '/api/settings', to: 'api#settings'

  post '/api/resend_confirm', to: 'api#resend_confirm', as: :resend_confirm
  post '/api/create_stripe_checkout', to: 'api#create_stripe_checkout'

  resources :comments do
    member do
      post :edit
      post :delete
      post :restore
      post :upvote
      post :unvote
      post :report
      post :unreport
      post :reply
    end
  end
  get '/comments', to: 'comments#index'
  get '/comments/:id/history', to: 'comments#history', as: 'comment_history'

  get '/auth/:provider/callback', to: 'sessions#omniauth_callback'
  get '/auth/:provider/disconnect',
    to: 'sessions#omniauth_disconnect', as: 'omniauth_disconnect'
  get '/auth/failure', to: 'sessions#omniauth_failure', as: 'omniauth_failure'
  post '/auth/create', to: 'sessions#omniauth_create', as: 'omniauth_create'

  get '/signup',   to: 'users#new', as: 'signup'
  post '/signup',  to: 'users#create'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/logout',   to: 'sessions#destroy'
  get '/signin',   to: redirect('/login')
  get '/signout',  to: redirect('/logout')

  get '/about',    to: 'static_pages#about'
  get '/version',  to: 'static_pages#version'
  get '/conduct',  to: 'static_pages#conduct'
  get '/legal',    to: 'static_pages#legal'
  get '/moderation',    to: 'static_pages#moderation'


  if Settings::JOBS_VISIBLE
    get '/jobs/success', to: 'static_pages#job_success'
    get '/jobs/submit',  to: 'static_pages#submit_job'
    get '/jobs/about',   to: 'static_pages#about_jobs'

    get '/jobs', to: 'static_pages#list_jobs'
  end

  get '/reset_password', to: 'password_resets#new', as: :reset_password
  post '/reset_password', to: 'password_resets#create'

  get '/reset_password/:id', to: 'password_resets#confirm', as: :reset_password_confirm
  post '/reset_password/:id', to: 'password_resets#submit'

  get '/settings', to: 'users#settings'
  post '/settings', to: 'users#settings'

  get '/settings/password', to: 'users#settings_password'
  post '/settings/password', to: 'users#settings_password'

  #resources :users, only: [:new, :create, :edit, :update, :destroy, :admin]
  get '/users/:id/subscriptions', to: 'users#subscriptions', as: 'subscriptions_user'
  get '/users/:id/activate/:confirmation_token', to: 'users#activate', as: 'activate_user'
  get '/feeds', to: 'users#feeds', as: 'feeds'

  get '/arxiv/:paper_uid/scites', to: 'papers#scites', paper_uid: /(.+\/.+|\d+.\d+)(v\d)?/, as: 'paper_scites'
  get '/arxiv/:feed/comments', to: 'comments#index', feed: /.+/, as: 'feed_comments'
  get '/arxiv/*paper_uid', to: 'papers#show', paper_uid: /.+\/.+|\d+.\d+(v\d)?/, as: 'paper'
  get '/arxiv/:feed', to: 'feeds#show', feed: /.+/, as: 'feed'#, constraints: NeedsUserConstraint

  get '/admin', to: 'admin/base#index', as: 'admin'
  post '/admin/alert', to: 'admin/base#alert', as: 'admin_alert'

  get '/admin/users/:username/edit', to: 'admin/users#edit', as: 'admin_edit_user'
  post '/admin/users/:username/update', to: 'admin/users#update', as: 'admin_update_user'
  post '/admin/users/:username/become', to: 'admin/users#become', as: 'admin_become_user'

  get '/:username/download_scites', to: 'users#download_scites', username: /.+/, as: 'user_download_scites'
  get '/:username/scites', to: 'users#scites', username: /.+/, as: 'user_scites'
  get '/:username/comments', to: 'users#comments', username: /.+/, as: 'user_comments'
  get '/:username/papers', to: 'users#papers', username: /.+/, as: 'user_papers'
  get '/:username', to: 'users#activity', username: /.+/, as: 'user'
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    before_action :load_user

    def edit
    end

    def become
      sign_in @user
      flash[:success] = "You are now signed in as #{@user.username}"
      redirect_to root_path
    end

    def update
      old = @user.attributes.dup

      user_params = params.required(:user)
        .permit(:fullname, :email, :username, :url, :organization, :location,
                :author_identifier, :about, :account_status)

      if @user.update(user_params)
        if old['email'] != @user.email
          @user.send_email_change_confirmation(old['email'])
        end

        flash[:success] = 'User has been successfully updated.'
      else
        flash[:error] = 'Failed to update user.'
      end

      render 'edit'
    end

    private

    def load_user
      @user = User.where("lower(username) = lower(?)", params[:username]).first!
    end
  end
end

app/controllers/users_controller.rb
require 'open-uri'
require 'data_helpers'

class UsersController < ApplicationController
  before_action :signed_in_user,
           only: [:feeds, :edit, :update, :destroy, :settings, :settings_password]

  before_action :correct_user, only: [:edit, :update, :destroy]

  before_action :profile_data, only: [:activity, :papers, :scites, :comments, :download_scites]

  def profile_data
    @user = User.where("lower(username) = lower(?)", params[:username]).first!
    rescue ActiveRecord::RecordNotFound
      return not_found
  end

  def activity
    @tab = :activity
    @activities = @user.activity_feed(25)

    render 'users/profile', formats: :html
  end

  def papers
    @tab = :papers
    @page = [1, params.fetch(:page, 1).to_s.to_i].max

    @authored_papers = @user.authored_papers.includes(:feeds, :authors).order('pubdate DESC').paginate(page: @page)
    @scited_by_uid = current_user.scited_by_uid(@authored_papers) if current_user

    render 'users/profile', formats: :html
  end

  def scites
    @tab = :scites
    @page = [1, params.fetch(:page, 1).to_s.to_i].max

    @scited_papers = @user.scited_papers
      .order("scites.created_at DESC")
      .includes(:feeds, :authors)
      .paginate(page: @page, per_page: 10)

    @scited_by_uid = current_user.scited_by_uid(@scited_papers) if current_user

    render 'users/profile', formats: :html
  end

  def download_scites
    @page = [1, params.fetch(:page, 1).to_s.to_i].max
    @per_page = 1000

    @scited_papers = @user.scited_papers
      .select("papers.*, scites.created_at as scite_created_at")
      .order("scites.created_at DESC")

    render json: @scited_papers[ [@scited_papers.length, @per_page * (@page - 1)].min, @per_page]
  end

  def comments
    @tab = :comments
    @page = [1, params.fetch(:page, 1).to_s.to_i].max

    @comments = @user.comments
      .where(hidden: false, deleted: false)
      .includes(:user, :paper)
      .paginate(page: @page, per_page: 20)

    render 'users/profile', formats: :html
  end

  def new
    if !signed_in?
      @user = User.new
    else
      #flash[:error] = "Sign out to create a new user!"
      redirect_to root_path
    end
  end

  def create
    if !signed_in?
      unless verify_recaptcha?(params["g-recaptcha-response"], 'submit')
        flash[:error] = "reCaptcha verification failed!"
        render 'new' and return
      end

      default_username = User.default_username(params[:user][:fullname])
      @user = User.new(params.required(:user).permit(:fullname, :email, :password).merge(username: default_username, password_confirmation: params[:user][:password]))

      if @user.save
        @user.send_signup_confirmation
        sign_in @user
        redirect_to root_path and return
      else
        flash[:error] = "Unable to sign up user"
        render 'new'
      end   
     
    else
      flash[:error] = "Sign out to create a new user!"
      redirect_to root_path
    end
  end

  def edit
  end

  def destroy
    user = User.find_by_id(params[:id])

    if user == current_user
      user.destroy
      flash[:success] = "Your profile has been deleted."
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def activate
    user = User.find_by_id(params[:id])

    if user && !user.email_confirmed? && user.confirmation_token == params[:confirmation_token]

      if user.confirmation_sent_at > 2.days.ago
        user.activate
        flash[:success] = "Your account has been activated."
        sign_in(user)
        redirect_to root_url
      else
        user.send_signup_confirmation
        flash[:error] = "Confirmation link has expired: a new confirmation email has been sent to #{user.email}"
        redirect_to root_url
      end
    else
      flash[:error] = "Account is already active or link is invalid!"
      redirect_to root_url
    end
  end

  # Big feed subscriptions page
  def feeds
    @user = current_user
    @subscribed_ids = @user.subscriptions.pluck(:feed_uid)
  end

  def settings
    @user = current_user
    return unless request.post?

    old_email = @user.email

    user_params = params.required(:user)
                        .permit(:fullname, :email, :username, :url, :organization, :location, :author_identifier, :about, :show_jobs, :email_about_replies, :email_about_comments_on_authored, :email_about_comments_on_scited, :email_about_reported_comments)

    # Handle some varying input forms of author identifiers
    # e.g. https://twitter.com/fishcorn/status/476046077733261313
    aid = user_params[:author_identifier]
    if m = aid.match(/\/([^\/]+)\/?\Z/)
      aid = m[1]
    end
    user_params[:author_identifier] = aid.downcase

    begin
      if @user.update(user_params)
        if old_email != @user.email
          @user.send_email_change_confirmation(old_email)
          sign_in @user
        end

        sign_in @user
        flash[:success] = "Profile updated"
      else
        flash[:error] = @user.errors.full_messages
      end
    rescue OpenURI::HTTPError
      flash[:error] = "The arXiv doesn't seem to have that author identifier, please double check"
    end
  end

  def settings_password
    @user = current_user
    return unless request.post?

    if @user.password_digest.nil? || @user.authenticate(params[:current_password])
      if params[:new_password] == params[:confirm_password]
        if @user.change_password(params[:new_password])
          sign_in @user
          flash[:success] = "Password changed successfully"
        else
          flash[:error] = @user.errors.full_messages
        end
      else
        flash[:error] = "New password confirmation does not match"
      end
    else
      flash[:error] = "Current password is incorrect"
    end
  end

  private
    def correct_user
      @user = User.find_by_username(params[:username])
      unless current_user?(@user)
        redirect_to(root_path)
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_url(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def gravatar_for(user, options = { size: 50 })
    image_tag(gravatar_url(user, options), alt: user.fullname, class: "gravatar")
  end
end

app/views/users/_activity.html.slim
#activityTab
  - @activities.each do |activity|
    - if activity.event == 'scite'
      .row.event class=(activity.event)
        .icon.col-md-1
          i.fa.fa-star
        .col-md-11
          = timeago(activity.created_at)
          .title
            | #{@user.fullname} scited #{link_to activity.paper.title, activity.paper}

    - elsif activity.event == 'subscribe'
      .row.event class=(activity.event)
        .col-md-1.icon
          i.fa.fa-list
        .col-md-11
          = timeago(activity.created_at)
          .title
            | #{@user.fullname} subscribed to #{link_to activity.feed.fullname, activity.feed}

    - elsif activity.event == 'comment'
      .row.event class=(activity.event) data-markup=(activity.comment.content)
        .col-md-1.icon
          i.fa.fa-comment
        .col-md-11
          = timeago(activity.created_at)
          .title
              | #{@user.fullname} commented on <a href="#{paper_url(activity.comment.paper)}##{activity.comment.id}">#{activity.comment.paper.title}</a>
          .content.well.tex2jax
            .body
              = simple_format(strip_tags(activity.comment.content))

    - elsif activity.event == 'authorship'
      .row.event class=(activity.event)
        .col-md-1.icon
          i.fa.fa-pencil
        .col-md-11
          = timeago(activity.created_at)
          .authorship
            .title
              | #{@user.fullname} published #{link_to activity.paper.title, activity.paper}
            .content.well
              = activity.paper.abstract

    - elsif activity.event == 'signup'
      .row.event class=(activity.event)
        .col-md-1.icon
          i.fa.fa-user
        .col-md-11
          = timeago(activity.created_at)
          .title
            | #{@user.fullname} joined SciRate

app/views/users/_comments.html.slim
#profileComments
  - if @user.comments_count == 0
    .well
      | No comments posted.
  - else
    = render @comments
    = will_paginate @comments

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
  <%= f.label :fullname %>
  <%= f.text_field :fullname %>
</div>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password, :autocomplete => :off %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, :autocomplete => :off %>
</div>

app/views/users/_papers.html.slim
#papersTab
  .well
    | Showing all papers from arXiv author <strong>#{@user.author_identifier}</strong>
  hr
  ul.papers
    = render partial: "papers/paper", collection: @authored_papers, locals: { showabs: false }
    = will_paginate @authored_papers

app/views/users/_scites.html.slim
#scitesTab
  - if @scited_papers.count == 0
    .well
      | No papers scited.
  - else
    .inline-search
      = form_tag(papers_search_path + '#results', method: :get) do |f|
        = label_tag :q, "Search query", class: 'sr-only'
        = text_field_tag :q, nil, class: 'form-control', placeholder: "Search Scites"
        = hidden_field_tag :advanced, "scited_by:#{@user.username}"

        button.btn.btn-primary.btn-right type="submit"
          i.fa.fa-search.icon-lg
      hr
      ul.papers
        = render partial: "papers/paper", collection: @scited_papers, locals: { showabs: false }
      = will_paginate @scited_papers

app/views/users/_short_paper.html.erb
<li class="papers">
   <%= render 'papers/paper_title', paper: paper %>
</li>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 30 %>
  <%= link_to user.fullname, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
  <% end %>
</li>

app/views/users/feeds.html.slim
- provide :title, "All Feeds"

- cache [:feeds, @subscribed_ids] do
  div id="subscriptions" class="container"
    h1 My Feeds

    | Please choose one or more feeds to subscribe to. Papers from subscribed feeds will appear on your <a href="/">home feed</a>.

    h2 Physics
    - Feed.in_order(['gr-qc', 'hep-ex', 'hep-lat', 'hep-ph', 'hep-th', 'math-ph', 'nucl-ex', 'nucl-th', 'quant-ph']).each do |feed|
      div.feed-card
        => feed.fullname
        | [<a href="#{url_for(feed)}">#{feed.uid}</a>]
        = render 'feeds/subscribe', feed: feed,
                 subscribed: @subscribed_ids.include?(feed.uid)

    - Feed.in_order(['astro-ph', 'cond-mat', 'physics', 'math', 'stat', 'cs', 'q-bio', 'q-fin', 'nlin']).each do |feed|
      h2= feed.fullname
      div.feed-card
        => feed.fullname
        | [<a href="#{url_for(feed)}">#{feed.uid}</a>]
        = render 'feeds/subscribe', feed: feed,
                 subscribed: @subscribed_ids.include?(feed.uid)

      - feed.children.order(:fullname).each do |feed|
        div.feed-card
          => feed.fullname
          | [<a href="#{url_for(feed)}">#{feed.uid}</a>]
          = render 'feeds/subscribe', feed: feed,
                   subscribed: @subscribed_ids.include?(feed.uid)

app/views/users/new.html.slim
- provide(:title, 'Join SciRate')

#signup.container
  .row
    .col-md-6
      h1 Join SciRate

      a.btn.btn-google href="/auth/google_oauth2"
        i
        span Sign up with Google

      hr

      = form_for(@user, url: signup_path(@user)) do |f|
        = render 'shared/error_messages', object: f.object
        .form-group
          = f.label :fullname, "Name"
          = f.text_field :fullname, class: 'form-control'
        .form-group
          = f.label :email
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :password
          = f.password_field :password, class: 'form-control'
        = f.submit "Sign up", class: 'btn btn-default g-recaptcha', 'data-sitekey': '6Lf7Q9QZAAAAAEHmCmtNAxA6svUoG-YMXSX8sBR0', 'data-action': 'submit', 'data-callback': 'onSubmit'

javascript:
  function onSubmit(token) {
     document.getElementById("new_user").submit();
   }

app/views/users/profile.html.haml
- provide :title, @user.name

.container#profile-page
  %table.table
    %tr
      %td
        %h1
          = gravatar_for @user, size: 100
          = @user.name

  .row
    .col-md-6
      %h3 Scites (#{@user.scites_count})
      - if @user.scites_count == 0
        %p No papers scited.
      - else
        %ul.nav.nav-tabs
          %li{ class: @scite_order == :scited ? 'active' : '' }
            = link_to "Sort by Scite Date", url_for(params.merge(scite_order: :scited))
          %li{ class: @scite_order == :published ? 'active' : '' }
            = link_to "Sort by Publication Date", url_for(params.merge(scite_order: :published))
        = render partial: "papers/paper", collection: @scited_papers, locals: { showabs: false }
        = will_paginate @scited_papers, param_name: 'scite_page'
    .col-md-6
      %h3 Comments (#{@user.comments_count})
      - if @user.comments_count == 0
        %p No comments posted.
      - else
        = render @comments
        = will_paginate @comments, param_name: 'comment_page'

app/views/users/profile.html.slim
- provide :title, @user.fullname
- provide :image, gravatar_url(@user, size: 200)

#profilePage.container
  #details.col-md-3
    div#profileImage
      - if @user == current_user
        a href="https://gravatar.com/emails"
          div.overlay
            i.fa.fa-pencil
            div.darken
          = gravatar_for(@user, size: 230)
      - else
        = gravatar_for(@user, size: 230)
    h1
      span.fullname= @user.fullname
      span.username = @user.username
    ul.user-info
      - if @user.can_admin?
        li.admin
          i.admin.fa.icon-fw.fa-sun-o
          span Admin
      - elsif @user.can_moderate?
        li.moderator
          i.moderator.fa.icon-fw.fa-certificate
          span Moderator

      - unless @user.organization.empty?
        li
          i.fa.icon-fw.fa-users
          span= @user.organization
      - unless @user.location.empty?
        li
          i.fa.icon-fw.fa-map-marker
          span= @user.location
      - unless @user.url.empty?
        li
          i.fa.icon-fw.fa-link
          = link_to @user.url, @user.url
      li
        i.fa.icon-fw.fa-clock-o
        span Joined #{@user.created_at.to_date.to_formatted_s(:rfc822)}
    ul.subscriptions
      - @user.subscriptions.order('feed_uid ASC').includes(:feed).each do |sub|
        li.badge
          a href=(feed_url sub.feed) title=(sub.feed.fullname)
            = sub.feed.uid
  .col-md-9
    ul.nav.nav-tabs
      li class=('active' if @tab == :activity)
        a href=(user_path @user)
          i.fa.icon-fw.fa-rss>
          | Activity
      - unless @user.author_identifier.empty?
        li class=('active' if @tab == :papers)
          a href=(user_papers_path @user)
            i.fa.icon-fw.fa-file-text-o>
            | Papers (#{@user.papers_count})
      li class=('active' if @tab == :comments)
        a href=(user_comments_path @user)
          i.fa.icon-fw.fa-comments>
          | Comments (#{@user.comments_count})
      li class=('active' if @tab == :scites)
        a href=(user_scites_path @user)
          i.fa.icon-fw.fa-star>
          | Scites (#{@user.scites_count})
      .pull-right
        - if current_user && current_user.can_admin?
          a.btn.btn-danger href=(admin_edit_user_path(@user))
            i.fa.icon-fw.fa-cog
            | Admin
        - if @user == current_user
          a.btn.btn-default href=(settings_path)
            i.fa.icon-fw.fa-pencil
            | Edit profile
          a.btn.btn-default href=(user_download_scites_path(@user, {:page => 1})) title="This downloads Scites in pages of 1000. View a different page by changing the query parameter in the URL."
            i.fa.icon-fw.fa-download
            | Download Scites (JSON)


    - if @tab == :activity
      - cache [:profile_activity, @user] do
        = render partial: 'users/activity'
    - elsif @tab == :papers
      - cache [:profile_papers, @user] do
        = render partial: 'users/papers'
    - elsif @tab == :scites
      - cache [:profile_scites, @user, params[:page]] do
        = render partial: 'users/scites'
    - elsif @tab == :comments
      = render partial: 'users/comments'

app/views/users/settings.html.slim
- provide :title, "Settings"

#settingsPage.container
  h1 Settings
  ul.nav.nav-tabs
    li.active
      a href=settings_path General
    li
      a href=settings_password_path Password
  = form_for(@user, url: settings_path, method: :post) do |f|
    table.table.table-striped.table-form
      tr
        td= f.label :fullname, "Name"
        td= f.text_field :fullname, class: 'form-control'
      tr
        td= f.label :username, "Username"
        td= f.text_field :username, class: 'form-control'
      tr
        td= f.label :email, "Email"
        td= f.email_field :email, class: 'form-control'
      tr
        - desc = "A personal website or other url"
        td= f.label :url, "URL"
        td= f.text_field :url, class: 'form-control', title: desc, placeholder: desc
      tr
        - desc = "Primary group you are affiliated with"
        td= f.label :organization, "Organization"
        td= f.text_field :organization, class: 'form-control', title: desc, placeholder: desc
      tr
        - desc = "Where you are in the world"
        td= f.label :location, "Location"
        td= f.text_field :location, class: 'form-control', title: desc, placeholder: desc
      tr
        - desc = "arXiv author identifier will be used to display papers on your profile"
        td
          = f.label :author_identifier, "Author Identifier"
          a href="http://arxiv.org/help/author_identifiers"
            sup
              | ?
        td= f.text_field :author_identifier, class: 'form-control', title: desc, placeholder: desc
      /
        tr
          - desc = "Some descriptive text about yourself"
          td= f.label :about
          td= f.text_area :about, class: 'form-control', title: desc, placeholder: desc

    .checkbox
      = f.check_box :show_jobs
      | Show me jobs
    .checkbox
      = f.check_box :email_about_replies
      | Email me about replies to my comments
    .checkbox
      = f.check_box :email_about_comments_on_authored
      | Email me about comments on papers I've written (needs author identifier)
    .checkbox
      = f.check_box :email_about_comments_on_scited
      | Email me about comments on papers I've scited
    - if @user.can_moderate?
      .checkbox
        = f.check_box :email_about_reported_comments
        i.moderator.fa.icon-fw.fa-certificate title="Special moderator function"
        | Email me about reported comments
    = f.submit "Save changes", class: "btn btn-default"

  p.google
    i> class="fa fa-google-plus-square"
    - if @user.auth_links.empty?
      = link_to "Enable Google login", "/auth/google_oauth2", id: "sign_in", method: :post
    - else
      | Connected to Google (#{@user.auth_links[0].auth.info.email})
      br
      = link_to "disconnect", omniauth_disconnect_path("google_oauth2")

  .gravatar
    => gravatar_for(@user)
    = link_to "change", "http://gravatar.com/emails", target: "_blank"

app/views/users/settings_password.html.slim
- provide :title, "Change Password"
.container
  h1 Change Password
  ul.nav.nav-tabs
    li= link_to 'General', '/settings'
    li.active= link_to 'Password', '/settings/password'
  - if !@user.auth_links.empty?
    br
    .alert.alert-success
      p
        | Please note that signing in with Google does not require a password.
  = form_tag do |f|
    table.table.table-striped.table-form
      - if @user.password_digest
        tr
          td= label_tag :current_password, "Current Password"
          td= password_field_tag :current_password, nil, class: 'form-control'
      tr
        td= label_tag :new_password, "New Password"
        td= password_field_tag :new_password, nil, class: 'form-control'
      tr
        td= label_tag :confirm_password, "Confirm Password"
        td= password_field_tag :confirm_password, nil, class: 'form-control'
    = submit_tag "Save changes", class: 'btn btn-default'